Repository TRIP-SPOT/SPOT-Server, pull requests merged in 2024-09, with the labels that each got.

#12 [Feature] Record(여행 기록) 생성 API 구현
  src/main/java/com/spot/spotserver/api/record/domain/Record.java
Labels: ✨feature

#17 [Feature] S3 연동 및 S3 API 작성
  build.gradle
  src/main/java/com/spot/spotserver/common/s3/S3Service.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: ✨feature

#19 [Feature] Record Entity 변경
  src/main/java/com/spot/spotserver/api/record/domain/Record.java
Labels: ✨feature

#20 [Feature] 토큰 재발급 기능 구현
  src/main/java/com/spot/spotserver/api/auth/controller/AuthController.java
  src/main/java/com/spot/spotserver/api/auth/dto/request/TokenRequest.java
  src/main/java/com/spot/spotserver/api/auth/jwt/JwtTokenProvider.java
  src/main/java/com/spot/spotserver/api/auth/jwt/redis/RefreshTokenService.java
  src/main/java/com/spot/spotserver/api/auth/jwt/redis/Token.java
  src/main/java/com/spot/spotserver/api/auth/jwt/redis/TokenRepository.java
  src/main/java/com/spot/spotserver/api/auth/service/AuthService.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
  src/main/java/com/spot/spotserver/config/SecurityConfig.java
Labels: ✨feature

#24 [Feature] CurrentUser 어노테이션 생성
  src/main/java/com/spot/spotserver/api/auth/service/AuthService.java
  src/main/java/com/spot/spotserver/common/annotation/CurrentUser.java
  src/main/java/com/spot/spotserver/common/annotation/CurrentUserArgumentResolver.java
  src/main/java/com/spot/spotserver/config/WebConfig.java
Labels: ✨feature

#26 [Fix] S3Service에서 S3Client Bean을 찾을 수 없는 문제 해결
  src/main/java/com/spot/spotserver/config/S3Config.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🐞bug

#27 [Feature] 사용자 닉네임 설정 API 구현
  src/main/java/com/spot/spotserver/api/auth/jwt/JwtTokenProvider.java
  src/main/java/com/spot/spotserver/api/auth/service/AuthService.java
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/api/user/domain/User.java
  src/main/java/com/spot/spotserver/api/user/dto/request/NicknameRequest.java
  src/main/java/com/spot/spotserver/api/user/dto/response/NicknameResponse.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/annotation/CurrentUserArgumentResolver.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#28 [Feature] 사용자 닉네임 수정 API 구현
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#30 [Feature] 프로필 이미지 설정 API 구현
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/api/user/domain/User.java
  src/main/java/com/spot/spotserver/api/user/dto/request/ProfileRequest.java
  src/main/java/com/spot/spotserver/api/user/dto/response/ProfileResponse.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
  src/main/java/com/spot/spotserver/common/s3/S3Service.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: ✨feature

#36 [Fix] 최초 로그인 시 사용자 생성 안되는 문제 해결
  src/main/java/com/spot/spotserver/api/auth/service/AuthService.java
Labels: 🐞bug

#39 [Feature] 프로필 배경색 설정 API 구현
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/api/user/domain/User.java
  src/main/java/com/spot/spotserver/api/user/dto/request/ColorRequest.java
  src/main/java/com/spot/spotserver/api/user/dto/response/ColorResponse.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#41 [Feature] 프로필 배경색 수정 API 구현
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#44 [Feature] 닉네임 조회 API 구현
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#46 [Feature] Record(여행 기록) 생성 API 구현
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/domain/City.java
  src/main/java/com/spot/spotserver/api/record/domain/Record.java
  src/main/java/com/spot/spotserver/api/record/domain/RecordImage.java
  src/main/java/com/spot/spotserver/api/record/domain/Region.java
  src/main/java/com/spot/spotserver/api/record/dto/RecordRequest.java
  src/main/java/com/spot/spotserver/api/record/dto/RecordResponse.java
  src/main/java/com/spot/spotserver/api/record/repository/RecordImageRepository.java
  src/main/java/com/spot/spotserver/api/record/service/RecordImageService.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
  src/main/java/com/spot/spotserver/api/spot/domain/Likes.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
  src/main/resources/application-local.yml
Labels: ✨feature

#47 [Feature] 지역 별 Record(여행 기록) 조회 API 구현
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/dto/RegionalRecordResponse.java
  src/main/java/com/spot/spotserver/api/record/repository/RecordImageRepository.java
  src/main/java/com/spot/spotserver/api/record/repository/RecordRepository.java
  src/main/java/com/spot/spotserver/api/record/service/RecordImageService.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#48 [Feature] 특정 Record(여행 기록) 상세 정보 조회 API 구현
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/repository/RecordImageRepository.java
  src/main/java/com/spot/spotserver/api/record/service/RecordImageService.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#49 [Feature] Record(여행 기록) 수정 API 구현
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/domain/Record.java
  src/main/java/com/spot/spotserver/api/record/dto/RecordUpdateRequest.java
  src/main/java/com/spot/spotserver/api/record/service/RecordImageService.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#50 [Feature] Record(여행 기록) 삭제 API 구현
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/repository/RecordImageRepository.java
  src/main/java/com/spot/spotserver/api/record/service/RecordImageService.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#51 [Feature] Record (여행 기록)의 대표 이미지 생성 API 구현
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/domain/RepresentativeImage.java
  src/main/java/com/spot/spotserver/api/record/dto/RepresentativeImageRequest.java
  src/main/java/com/spot/spotserver/api/record/dto/RepresentativeImageResponse.java
  src/main/java/com/spot/spotserver/api/record/repository/RepresentativeImageRepository.java
  src/main/java/com/spot/spotserver/api/record/service/RepresentativeImageService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#53 [Feature] 대표 이미지 전체 조회 API 구현
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/dto/RepresentativeImageResponse.java
  src/main/java/com/spot/spotserver/api/record/service/RepresentativeImageService.java
Labels: ✨feature

#54 [Feature] 대표 이미지 수정 API 구현
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/domain/RepresentativeImage.java
  src/main/java/com/spot/spotserver/api/record/service/RepresentativeImageService.java
Labels: ✨feature

#56 [Feature] 퀴즈 조회 기능 구현
  src/main/java/com/spot/spotserver/api/quiz/controller/QuizController.java
  src/main/java/com/spot/spotserver/api/quiz/domain/Quiz.java
  src/main/java/com/spot/spotserver/api/quiz/dto/QuizResponse.java
  src/main/java/com/spot/spotserver/api/quiz/service/QuizService.java
Labels: ✨feature

#58 [Feature] 퀴즈 정답 확인 기능 구현
  src/main/java/com/spot/spotserver/api/quiz/controller/QuizController.java
  src/main/java/com/spot/spotserver/api/quiz/domain/Badge.java
  src/main/java/com/spot/spotserver/api/quiz/domain/Quiz.java
  src/main/java/com/spot/spotserver/api/quiz/dto/AnswerCheckRequest.java
  src/main/java/com/spot/spotserver/api/quiz/dto/AnswerCheckResponse.java
  src/main/java/com/spot/spotserver/api/quiz/repository/BadgeRepository.java
  src/main/java/com/spot/spotserver/api/quiz/service/QuizService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#60 [Feature] 각 촬영지(spot)의 상세정보 조회 API 구현
  build.gradle
  src/main/java/com/spot/spotserver/api/spot/client/CommonInfoClient.java
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/CommonInfoResponse.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/SpotDetailsResponse.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
  src/main/java/com/spot/spotserver/config/FeignConfig.java
Labels: ✨feature

#64 [Hotfix] Region, City 반환 형태를 ordinal로 변경
  src/main/java/com/spot/spotserver/api/record/dto/RecordResponse.java
  src/main/java/com/spot/spotserver/api/record/dto/RegionalRecordResponse.java
  src/main/java/com/spot/spotserver/api/record/dto/RepresentativeImageResponse.java
  src/main/java/com/spot/spotserver/api/record/service/RecordImageService.java
Labels: ✨feature

#66 [Feature] 각 촬영지 주변 장소 리스트 조회 API 구현
  src/main/java/com/spot/spotserver/api/spot/client/LocationBasedListClient.java
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/domain/Spot.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/LocationBasedResponse.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/SpotAroundResponse.java
  src/main/java/com/spot/spotserver/api/spot/repository/SpotRepository.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#65 [Feature] 현재 위치 기준 반경 20km 이내 촬영지 검색 기능 구현
  src/main/java/com/spot/spotserver/api/quiz/controller/QuizController.java
  src/main/java/com/spot/spotserver/api/quiz/repository/QuizRepository.java
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/domain/Spot.java
  src/main/java/com/spot/spotserver/api/spot/domain/Work.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/AccessibleSpotResponse.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#73 [Bug] Region, City import 수정
  src/main/java/com/spot/spotserver/api/quiz/domain/Badge.java
  src/main/java/com/spot/spotserver/api/quiz/domain/Quiz.java
  src/main/java/com/spot/spotserver/api/quiz/dto/QuizResponse.java
  src/main/java/com/spot/spotserver/api/quiz/repository/BadgeRepository.java
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/domain/Record.java
  src/main/java/com/spot/spotserver/api/record/domain/RepresentativeImage.java
  src/main/java/com/spot/spotserver/api/record/dto/RecordRequest.java
  src/main/java/com/spot/spotserver/api/record/dto/RecordResponse.java
  src/main/java/com/spot/spotserver/api/record/dto/RegionalRecordResponse.java
  src/main/java/com/spot/spotserver/api/record/dto/RepresentativeImageRequest.java
  src/main/java/com/spot/spotserver/api/record/dto/RepresentativeImageResponse.java
  src/main/java/com/spot/spotserver/api/record/repository/RecordRepository.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
  src/main/java/com/spot/spotserver/api/schedule/domain/Location.java
  src/main/java/com/spot/spotserver/api/schedule/domain/Schedule.java
Labels: 🐞bug

#76 [Feature] 예외 처리 세팅
  src/main/java/com/spot/spotserver/common/advice/BaseException.java
  src/main/java/com/spot/spotserver/common/advice/ControllerExceptionAdvice.java
Labels: ✨feature

#79 [Feature] 여행 일정 삭제 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#84 [Refactor] Record 도메인 예외 처리 리팩토링
  src/main/java/com/spot/spotserver/api/record/exception/RecordImageNotFoundException.java
  src/main/java/com/spot/spotserver/api/record/exception/RecordImageProcessingException.java
  src/main/java/com/spot/spotserver/api/record/exception/RecordNotFoundException.java
  src/main/java/com/spot/spotserver/api/record/exception/RepresentativeImageNotFoundException.java
  src/main/java/com/spot/spotserver/api/record/service/RecordImageService.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
  src/main/java/com/spot/spotserver/api/record/service/RepresentativeImageService.java
  src/main/java/com/spot/spotserver/common/payload/ErrorCode.java
  src/main/java/com/spot/spotserver/common/s3/S3Service.java
  src/main/java/com/spot/spotserver/common/s3/exception/FileConversionException.java
  src/main/java/com/spot/spotserver/common/s3/exception/S3UploadException.java
Labels: ♻️refactor

#86 [Bug] Content-Type 'application/octet-stream' is not supported 에러 해결
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/dto/RecordRequest.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
Labels: 🐞bug

#88 [Refactor] Token 및 User 도메인 예외 처리 리팩토링
  src/main/java/com/spot/spotserver/api/auth/exception/EmptyJwtTokenException.java
  src/main/java/com/spot/spotserver/api/auth/exception/ExpiredJwtTokenException.java
  src/main/java/com/spot/spotserver/api/auth/exception/InvalidJwtTokenException.java
  src/main/java/com/spot/spotserver/api/auth/exception/JwtCustomException.java
  src/main/java/com/spot/spotserver/api/auth/exception/OAuth2TokenException.java
  src/main/java/com/spot/spotserver/api/auth/exception/UnsupportedJwtTokenException.java
  src/main/java/com/spot/spotserver/api/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/spot/spotserver/api/auth/jwt/JwtTokenProvider.java
  src/main/java/com/spot/spotserver/api/auth/service/AuthService.java
  src/main/java/com/spot/spotserver/api/user/exception/UserNotFoundException.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/advice/BaseException.java
  src/main/java/com/spot/spotserver/common/payload/ErrorCode.java
Labels: ♻️refactor

#90 [Feature] 여행 일정 기간 수정 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/domain/Schedule.java
  src/main/java/com/spot/spotserver/api/schedule/dto/ScheduleDurationUpdateRequest.java
  src/main/java/com/spot/spotserver/api/schedule/dto/ScheduleDurationUpdateResponse.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#91 [Refactor] 카카오 로그인 Request Param 인가코드 -> 카카오 accessToken으로 로직 수정
  src/main/java/com/spot/spotserver/api/auth/controller/AuthController.java
  src/main/java/com/spot/spotserver/api/auth/service/AuthService.java
  src/main/java/com/spot/spotserver/common/payload/ErrorCode.java
Labels: ♻️refactor

#92 [Feature] 여행 일정 배너 사진 변경 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/domain/Schedule.java
  src/main/java/com/spot/spotserver/api/schedule/dto/ScheduleImageUpdateResponse.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#94 [Feature] Region, City 요청, 응답 형태 Integer로 변경
  src/main/java/com/spot/spotserver/api/quiz/controller/QuizController.java
  src/main/java/com/spot/spotserver/api/quiz/domain/Quiz.java
  src/main/java/com/spot/spotserver/api/quiz/dto/AnswerCheckRequest.java
  src/main/java/com/spot/spotserver/api/quiz/dto/AnswerCheckResponse.java
  src/main/java/com/spot/spotserver/api/quiz/dto/QuizResponse.java
  src/main/java/com/spot/spotserver/api/quiz/service/QuizService.java
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/dto/RecordRequest.java
  src/main/java/com/spot/spotserver/api/schedule/dto/ScheduleRequest.java
  src/main/java/com/spot/spotserver/api/schedule/dto/ScheduleResponse.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/AccessibleSpotResponse.java
Labels: ✨feature

#96 [HOTFIX] 배포 환경에서 발생하는 로그인 에러 해결
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🐞bug, ⚙️setting

#97 [Feature] 주변 장소의 상세 정보 조회 API 구현
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#98 [Feature] 여행 일정 목록 조회 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/dto/ScheduleResponse.java
  src/main/java/com/spot/spotserver/api/schedule/repository/ScheduleRepository.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#101 [Feature] 여행 일정에 장소 추가 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/domain/Location.java
  src/main/java/com/spot/spotserver/api/schedule/dto/LocationRequest.java
  src/main/java/com/spot/spotserver/api/schedule/dto/LocationResponse.java
  src/main/java/com/spot/spotserver/api/schedule/repository/LocationRepository.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#102 [Feature] 여행 일정에 포함된 장소 삭제 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#104 [Feature] Schedule DTO에 image 필드 추가
  src/main/java/com/spot/spotserver/api/schedule/dto/ScheduleResponse.java
Labels: ✨feature

#108 [Feature] 여행 일정 상세 내용 조회 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/dto/DetailedScheduleResponse.java
  src/main/java/com/spot/spotserver/api/schedule/repository/LocationRepository.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#109 [Feature] 촬영지 좋아요 누르기 & 삭제 API 구현
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/domain/Likes.java
  src/main/java/com/spot/spotserver/api/spot/exception/LikeAlreadyExistException.java
  src/main/java/com/spot/spotserver/api/spot/exception/LikeNotFoundException.java
  src/main/java/com/spot/spotserver/api/spot/repository/LikesRepository.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
  src/main/java/com/spot/spotserver/common/payload/ErrorCode.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#111 [Feature] 일정의 담은 Spot 조회 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/domain/SelectedSpot.java
  src/main/java/com/spot/spotserver/api/schedule/dto/request/LocationRequest.java
  src/main/java/com/spot/spotserver/api/schedule/dto/request/ScheduleDurationUpdateRequest.java
  src/main/java/com/spot/spotserver/api/schedule/dto/request/ScheduleRequest.java
  src/main/java/com/spot/spotserver/api/schedule/dto/response/DetailedScheduleResponse.java
  src/main/java/com/spot/spotserver/api/schedule/dto/response/LocationResponse.java
  src/main/java/com/spot/spotserver/api/schedule/dto/response/ScheduleDurationUpdateResponse.java
  src/main/java/com/spot/spotserver/api/schedule/dto/response/ScheduleImageUpdateResponse.java
  src/main/java/com/spot/spotserver/api/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/spot/spotserver/api/schedule/dto/response/SelectedSpotResponse.java
  src/main/java/com/spot/spotserver/api/schedule/dto/response/SelectedSpotsResponse.java
  src/main/java/com/spot/spotserver/api/schedule/repository/SelectedSpotRepository.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
  src/main/resources/application.yml
Labels: ✨feature

#112 [Feature] 촬영지 및 주변 장소 조회 DTO 수정
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/AroundDetailsResponse.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/SpotDetailsResponse.java
  src/main/java/com/spot/spotserver/api/spot/exception/SpotNotFoundException.java
  src/main/java/com/spot/spotserver/api/spot/repository/LikesRepository.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: ✨feature

#113 [Feature] 메인화면 촬영지 목록 조회 API 구현
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/TopLikedSpotResponse.java
  src/main/java/com/spot/spotserver/api/spot/repository/LikesRepository.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#114 [Feature] TopLikedSpotResponse에 id 필드 추가
  src/main/java/com/spot/spotserver/api/spot/dto/response/TopLikedSpotResponse.java
Labels: ✨feature

#116 [Fix] 존재하지 않는 Like에 대해 LikeAlreadyExistException 발생하는 문제 해결
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: 🐞bug

#118 [Feature] 특정 작품에 대한 촬영지 목록 검색 API 구현
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/domain/Work.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/SpotSearchResponse.java
  src/main/java/com/spot/spotserver/api/spot/exception/WorkNotFoundException.java
  src/main/java/com/spot/spotserver/api/spot/repository/SpotRepository.java
  src/main/java/com/spot/spotserver/api/spot/repository/WorkRepository.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
  src/main/java/com/spot/spotserver/common/payload/ErrorCode.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#120 [Feature] 메인화면 촬영지 목록 좋아요 갯수 비교 불가시 임의로 조회
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: ✨feature

#121 [Refactor] SpotType enum으로 별도 관리
  src/main/java/com/spot/spotserver/api/schedule/domain/LocationType.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
  src/main/java/com/spot/spotserver/common/domain/SpotType.java
Labels: ♻️refactor

#123 [Fix] Schedule 생성 요청 application/octet-stream' is not supported 에러 해결
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/dto/request/ScheduleRequest.java
Labels: 🐞bug

#126 [Feature] 일정에 Spot 담기 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/dto/request/SelectedSpotRequest.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#129 [Refactor] Region, City Enum 저장 방식 Ordinal로 변경
  src/main/java/com/spot/spotserver/api/quiz/domain/Badge.java
  src/main/java/com/spot/spotserver/api/quiz/domain/Quiz.java
  src/main/java/com/spot/spotserver/api/record/domain/Record.java
  src/main/java/com/spot/spotserver/api/record/domain/RepresentativeImage.java
  src/main/java/com/spot/spotserver/api/schedule/domain/Schedule.java
  src/main/java/com/spot/spotserver/api/spot/domain/Spot.java
  src/main/java/com/spot/spotserver/common/domain/City.java
Labels: ♻️refactor

#132 [Bug] 일정 생성 중, Location의 일자 별 배치 오류 해결
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: 🐞bug

#133 [Feature] API spec 변경에 따른 '여행 기록 이미지 수정 API' 변경 기능 구현
  src/main/java/com/spot/spotserver/api/record/dto/RecordUpdateRequest.java
  src/main/java/com/spot/spotserver/api/record/repository/RecordImageRepository.java
  src/main/java/com/spot/spotserver/api/record/service/RecordImageService.java
Labels: ✨feature

#134 [Refactor] 검색 결과 없는 경우, 에러 처리 대신 빈배열 반환으로 로직 수정
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: ♻️refactor

#136 [Fix] 촬영지 상세 정보 조회 시, contentId가 동일한 데이터로 인해 발생하는 NonUniqueResultException 문제 해결
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/SpotDetailsResponse.java
  src/main/java/com/spot/spotserver/api/spot/repository/SpotRepository.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: 🐞bug

#137 [Fix] 주변 장소 조회 시, contentId가 동일한 데이터로 인해 발생하는 NonUniqueResultException 문제 해결
  src/main/java/com/spot/spotserver/api/spot/controller/SpotController.java
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: 🐞bug

#140 [Bug] 일정에 장소 담는 기능 API에 누락된 schedule_id 추가
  src/main/java/com/spot/spotserver/api/schedule/controller/ScheduleController.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: 🐞bug

#143 [Fix] Record 수 요청 application/octet-stream' is not supported 에러 해결
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/dto/RecordUpdateRequest.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
Labels: 🐞bug

#145 [Feature] 주변 장소 조회 시 지정하는 반경 수정
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: ✨feature

#151 [Feature] 반경 내에 해당하는 퀴즈가 없는 경우 빈배열을 반환하도록 로직 수정
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: ✨feature

#152 [Feature] 좋아요한 장소 조회 API 구현
  src/main/java/com/spot/spotserver/api/spot/domain/Likes.java
  src/main/java/com/spot/spotserver/api/spot/dto/response/UserLikedSpotsResponse.java
  src/main/java/com/spot/spotserver/api/spot/repository/LikesRepository.java
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#154 [Feature] 일정에 Location 추가 시, 일자 지정 기능 구현
  src/main/java/com/spot/spotserver/api/schedule/dto/request/LocationRequest.java
  src/main/java/com/spot/spotserver/api/schedule/service/ScheduleService.java
Labels: ✨feature

#157 [Fix] 좋아요 삭제 시 발생하는 문제 해결
  src/main/java/com/spot/spotserver/api/spot/domain/Likes.java
Labels: 🐞bug

#159 [Refactor] Record 수정 API null 처리 방식 변경
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
Labels: ♻️refactor

#161 [Fix] 토큰 재발급 시 발생하는 401 에러 해결
  src/main/java/com/spot/spotserver/api/auth/jwt/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: 🐞bug

#163 [Bug] 대표 이미지 잘못 서빙되는 오류
  src/main/java/com/spot/spotserver/api/record/controller/RecordController.java
  src/main/java/com/spot/spotserver/api/record/repository/RepresentativeImageRepository.java
  src/main/java/com/spot/spotserver/api/record/service/RepresentativeImageService.java
Labels: 🐞bug

#165 [Bug] 퀴즈 풀기 기능 오류
  src/main/java/com/spot/spotserver/api/quiz/controller/QuizController.java
  src/main/java/com/spot/spotserver/api/quiz/domain/Quiz.java
  src/main/java/com/spot/spotserver/api/quiz/dto/AnswerCheckResponse.java
  src/main/java/com/spot/spotserver/api/quiz/dto/QuizResponse.java
  src/main/java/com/spot/spotserver/api/quiz/repository/QuizRepository.java
  src/main/java/com/spot/spotserver/api/quiz/service/QuizService.java
Labels: 🐞bug

#167 [Feature] UserLikedSpotsResponse 필드 추가
  src/main/java/com/spot/spotserver/api/spot/dto/response/UserLikedSpotsResponse.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
Labels: ✨feature

#169 [Feature] User 도메인 profileLevel 필드 추가 및 등급 업데이트 메소드 구현
  src/main/java/com/spot/spotserver/api/user/domain/ProfileLevel.java
  src/main/java/com/spot/spotserver/api/user/domain/User.java
  src/main/resources/application.yml
Labels: ✨feature

#171 [Feature] 반경 20km 이내 스팟 조회 기능에 가까운 순 5개 제한 기능 추가
  src/main/java/com/spot/spotserver/api/spot/service/SpotService.java
Labels: ✨feature

#172 [Feature] Record 추가 시, 뱃지 생성 기능 추가 구현
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
Labels: ✨feature

#174 [Refactor] Badge를 Region 단위에서 City 단위로 수정
  src/main/java/com/spot/spotserver/api/quiz/domain/Badge.java
  src/main/java/com/spot/spotserver/api/quiz/repository/BadgeRepository.java
  src/main/java/com/spot/spotserver/api/quiz/service/QuizService.java
  src/main/java/com/spot/spotserver/api/user/domain/User.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
Labels: ♻️refactor

#179 [Feature] 뱃지 생성 API 구현
  src/main/java/com/spot/spotserver/api/badge/controller/BadgeController.java
  src/main/java/com/spot/spotserver/api/badge/domain/AcquisitionType.java
  src/main/java/com/spot/spotserver/api/badge/domain/Badge.java
  src/main/java/com/spot/spotserver/api/badge/dto/BadgeRequest.java
  src/main/java/com/spot/spotserver/api/badge/repository/BadgeRepository.java
  src/main/java/com/spot/spotserver/api/badge/service/BadgeService.java
Labels: ✨feature

#183 [Feature] Badge 도메인 분리에 따른 기존 로직 변경
  src/main/java/com/spot/spotserver/api/badge/dto/BadgeRequest.java
  src/main/java/com/spot/spotserver/api/badge/service/BadgeService.java
  src/main/java/com/spot/spotserver/api/quiz/domain/Badge.java
  src/main/java/com/spot/spotserver/api/quiz/repository/BadgeRepository.java
  src/main/java/com/spot/spotserver/api/quiz/service/QuizService.java
  src/main/java/com/spot/spotserver/api/record/service/RecordService.java
  src/main/java/com/spot/spotserver/api/user/domain/User.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#185 [Feature] 사용자 등급 조회 API 구현
  src/main/java/com/spot/spotserver/api/badge/repository/BadgeRepository.java
  src/main/java/com/spot/spotserver/api/badge/service/BadgeService.java
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/api/user/domain/User.java
  src/main/java/com/spot/spotserver/api/user/dto/response/ProfileLevelResponse.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#187 [Feature] 좋아요한 촬영지 카드에 작품명 추가
  src/main/java/com/spot/spotserver/api/spot/dto/response/UserLikedSpotsResponse.java
Labels: ✨feature

#193 [Feature] 사용자 등급 조회 API 구현
  src/main/java/com/spot/spotserver/api/badge/repository/BadgeRepository.java
  src/main/java/com/spot/spotserver/api/badge/service/BadgeService.java
  src/main/java/com/spot/spotserver/api/user/controller/UserController.java
  src/main/java/com/spot/spotserver/api/user/domain/User.java
  src/main/java/com/spot/spotserver/api/user/dto/response/ProfileLevelResponse.java
  src/main/java/com/spot/spotserver/api/user/service/UserService.java
  src/main/java/com/spot/spotserver/common/payload/SuccessCode.java
Labels: ✨feature

#195 [Feature] 좋아요한 촬영지 카드에 작품명 추가
  src/main/java/com/spot/spotserver/api/spot/dto/response/UserLikedSpotsResponse.java
Labels: ✨feature

#196 [Refactor] 주변 장소 조회 시 기준 장소 포함되지 않도록 로직 수정
  src/main/java/com/spot/spotserver/api/spot/dto/response/SpotAroundResponse.java
Labels: ♻️refactor
